### ISSUE TITLE
Notify Characteristic

### ISSUE THREAD

**Issue by ghost** [DerekGn/WinRtBle#2]
if GattClientCharacteristicConfigurationDescriptorValue is Notify,how can i get the Value of Characteristic?

**Comment by DerekGn** [comment]
You will have to register a callback on the GattCharacteristic.ValueChanged Event

https://docs.microsoft.com/en-us/uwp/api/windows.devices.bluetooth.genericattributeprofile.gattcharacteristic.valuechanged

The callback that you create will be invoked when the BLE value changes here is an example lambda function that can be used to handle the notification. You can also create a dedicated method if you do not want to use a lambda function.

```C++
if (c.CharacteristicProperties() == GattCharacteristicProperties::Notify)
{
	c.ValueChanged([](GattCharacteristic const& charateristic, GattValueChangedEventArgs const& args)
	{
		std::wcout << std::hex <<
			"\t\tNotified GattCharacteristic - Guid: [" << guidToString(charateristic.Uuid()) << "]" << std::endl;

		DataReader reader = DataReader::FromBuffer(args.CharacteristicValue());

		// Note this assumes value is string the characteristic type must be determined before reading
		// This can display junk or maybe blowup
		std::wcout << "\t\t\tCharacteristic Data - [" << reader.ReadString(args.CharacteristicValue().Length()).c_str() << "]" << std::endl;
	});
}
```
The code has been modifed with the above
